#!/usr/bin/env bash
# Self-contained deploy bundle: unified server dist + npm pack tarballs + deploy manifests.
# Railway runs only: npm install --omit=dev --ignore-scripts (no vendor/, no git fetch of project-bridge).
# Run locally before railway up / mtx deploy (requires sibling project-bridge or PROJECT_BRIDGE_ROOT).
#
# Produces:
#   targets/server/dist/              — mirrored from project-bridge (server build)
#   targets/client/dist/              — mirrored Vite web app (build:client; required for production static UI)
#   targets/server/npm-packs/*.tgz    — packed @meanwhile-together/* workspaces
#   package.deploy.json + package-lock.deploy.json — full prod deps; Railway npm install materializes node_modules
#   .railway-self-contained           — marker for install/build scripts
#
# Commit or upload dist + npm-packs/ (mtx deploy uses railway up --no-gitignore).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PB="${PROJECT_BRIDGE_ROOT:-$ROOT/../project-bridge}"

if [ ! -f "$PB/package.json" ]; then
  echo "prepare-railway-artifact: project-bridge not found at $PB" >&2
  echo "  Set PROJECT_BRIDGE_ROOT or place project-bridge next to this repo (../project-bridge)." >&2
  exit 1
fi

if [ "${MTX_SKIP_PAYLOAD_VENDOR:-}" != "1" ] && [ -f "$ROOT/config/server.json" ]; then
  echo "==> prepare-railway-artifact: vendor + build path payloads from config/server.json"
  VENDOR_PAYLOADS_SCRIPT="${MTX_VENDOR_PAYLOADS_SCRIPT:-}"
  if [ -z "$VENDOR_PAYLOADS_SCRIPT" ] && [ -f "$ROOT/../MTX/lib/vendor-payloads-from-config.sh" ]; then
    VENDOR_PAYLOADS_SCRIPT="$ROOT/../MTX/lib/vendor-payloads-from-config.sh"
  fi
  if [ -z "$VENDOR_PAYLOADS_SCRIPT" ] || [ ! -f "$VENDOR_PAYLOADS_SCRIPT" ]; then
    echo "prepare-railway-artifact: MTX vendor script not found (expected ../MTX/lib/vendor-payloads-from-config.sh next to this org repo)." >&2
    echo "  Set MTX_VENDOR_PAYLOADS_SCRIPT to the absolute path of vendor-payloads-from-config.sh, or clone the MTX repo as a sibling of this org." >&2
    exit 1
  fi
  bash "$VENDOR_PAYLOADS_SCRIPT" "$ROOT" || exit 1
fi

echo "==> prepare-railway-artifact: unified server build (org config -> project-bridge)"
_ORG_BUILD_IMPL=""
if [ -n "${MTX_ROOT:-}" ] && [ -f "$MTX_ROOT/project/org-build-server.sh" ]; then
  _ORG_BUILD_IMPL="$MTX_ROOT/project/org-build-server.sh"
elif [ -f "$ROOT/../MTX/project/org-build-server.sh" ]; then
  _ORG_BUILD_IMPL="$(cd "$ROOT/../MTX" && pwd)/project/org-build-server.sh"
elif [ -f "$ROOT/../../MTX/project/org-build-server.sh" ]; then
  _ORG_BUILD_IMPL="$(cd "$ROOT/../../MTX" && pwd)/project/org-build-server.sh"
fi
if [ -n "$_ORG_BUILD_IMPL" ]; then
  bash "$_ORG_BUILD_IMPL" "$ROOT"
else
  bash "$ROOT/scripts/org-build-server.sh"
fi

echo "==> prepare-railway-artifact: bundle prisma schemas + migrations for runtime migrate deploy"
# Prisma 7 forbids `url` in `datasource db {}`; it must come from `prisma.config.ts`.
# We copy the generated schema (provider=postgresql, no url) and emit a minimal, self-contained
# `prisma.config.ts` next to it that reads DATABASE_URL from the environment. railway-migrate.mjs
# cwd's into each schema dir so Prisma auto-discovers this config.
(
  cd "$PB"
  DATABASE_PROVIDER=postgresql npx --yes tsx scripts/prepare-prisma-schema.ts
)
rm -rf "$ROOT/prisma"
mkdir -p "$ROOT/prisma"
for target in app backend; do
  if [ ! -f "$PB/prisma/$target/schema.prisma" ]; then
    echo "prepare-railway-artifact: missing $PB/prisma/$target/schema.prisma — did prepare-prisma-schema.ts run?" >&2
    exit 1
  fi
  mkdir -p "$ROOT/prisma/$target"
  rsync -a --delete "$PB/prisma/$target/migrations/" "$ROOT/prisma/$target/migrations/" 2>/dev/null || true
  # Copy schema verbatim (Prisma 7 wants no `url` in schema) and scrub any stray `url` line just in case.
  node - "$PB/prisma/$target/schema.prisma" "$ROOT/prisma/$target/schema.prisma" <<'NODE'
const fs = require('fs');
const [src, dst] = process.argv.slice(2);
let s = fs.readFileSync(src, 'utf8');
s = s.replace(/datasource\s+db\s*\{([^}]*)\}/m, (_m, body) => {
  const scrubbed = body
    .split('\n')
    .filter((line) => !/^\s*url\s*=/.test(line))
    .join('\n')
    .replace(/\s+$/, '');
  return `datasource db {${scrubbed}\n}`;
});
fs.mkdirSync(require('path').dirname(dst), { recursive: true });
fs.writeFileSync(dst, s);
NODE
  # Emit a minimal, self-contained prisma.config.ts next to the schema. Prisma 7 CLI auto-discovers
  # this file from cwd; railway-migrate.mjs cd's into the schema dir before spawning `prisma migrate`.
  cat > "$ROOT/prisma/$target/prisma.config.ts" <<'TS'
// Auto-generated by prepare-railway-artifact.sh. Do not hand-edit in the deploy bundle.
// Prisma 7 CLI loads this config (same dir as schema.prisma) to wire DATABASE_URL at migrate time.
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));

const url = process.env.DATABASE_URL;
if (!url) {
  throw new Error(
    'DATABASE_URL is required to run Prisma migrate against this bundle. ' +
      'Set it on the service (Railway wires this automatically when a Postgres plugin is attached).',
  );
}

const datasource: { url: string; shadowDatabaseUrl?: string } = { url };
const shadow =
  process.env.DATABASE_SHADOW_URL ??
  process.env.DATABASE_DIRECT_URL ??
  process.env.SHADOW_DATABASE_URL;
if (shadow) datasource.shadowDatabaseUrl = shadow;

export default {
  schema: path.resolve(here, 'schema.prisma'),
  migrations: {
    path: path.resolve(here, 'migrations'),
  },
  datasource,
};
TS
done
mkdir -p "$ROOT/scripts"
cp -a "$PB/scripts/railway-migrate.mjs" "$ROOT/scripts/railway-migrate.mjs"

echo "==> prepare-railway-artifact: generate deploy manifests (npm pack + lockfile)"
bash "$ROOT/scripts/generate-railway-deploy-manifest.sh"

touch "$ROOT/.railway-self-contained"

echo ""
echo "✅ Self-contained bundle ready."
echo "   Deploy: mtx deploy  (swaps config/server.json.railway for upload when path payloads were vendored)"
echo "   Or: railway up --no-gitignore — if server.json.railway exists, copy it over config/server.json first."
echo "   Railway install: npm install only — no project-bridge clone."
echo "   Re-run this script after config/ or project-bridge dependency changes."
